name: Archive Charity Commission register data

on:
  schedule:
    - cron: '0 2 * * *'  # Adjust the schedule as needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch files
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          mkdir -p archive
          wget -O archive/publicextract.charity.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity.zip
          wget -O archive/publicextract.charity_annual_return_history.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_annual_return_history.zip
          wget -O archive/publicextract.charity_annual_return_parta.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_annual_return_parta.zip
          wget -O archive/publicextract.charity_annual_return_partb.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_annual_return_partb.zip
          wget -O archive/publicextract.charity_area_of_operation.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_area_of_operation.zip
          wget -O archive/publicextract.charity_classification.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_classification.zip
          wget -O archive/publicextract.charity_event_history.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_event_history.zip
          wget -O archive/publicextract.charity_governing_document.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_governing_document.zip
          wget -O archive/publicextract.charity_other_names.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_other_names.zip
          wget -O archive/publicextract.charity_other_regulators.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_other_regulators.zip
          wget -O archive/publicextract.charity_policy.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_policy.zip
          wget -O archive/publicextract.charity_published_report.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_published_report.zip
          wget -O archive/publicextract.charity_trustee.zip https://ccewuksprdoneregsadata1.blob.core.windows.net/data/json/publicextract.charity_trustee.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: archive/

  commit_changes:
    needs: fetch_file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: archive
          path: archive/

      - name: Commit changes
        run: |
          sudo apt-get update && sudo apt-get install -y git
          git lfs install
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git checkout main
          ls -lah archive/
          git add archive/
          git diff-index --quiet HEAD || (git commit -m "update archive" && git push https://oauth2:${{ secrets.ARCHIVE_CI_TOKEN }}@github.com/dataactivists/charity_commission_register_archive.git main)
